#!/bin/sh
# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2018.2.2
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

# The next line restarts using autoesl tclsh \


# run as bash ./change_parallel.sh
cd ..
#  parallel.h
echo ".................generating parallel.h"
cd   ./parallel.c 
bash ./parallel.sh
cd  ..  

#syntesize generated SIMD core
echo ".................syntesizing design"
bash ./_UserDefinedPrimitives/call_vivado_syn.sh

cd ./_UserDefinedPrimitives



